package com.puer.wsclient.ykd.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-22T09:51:49.947+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.example.org/Ec/", name = "Ec")
@XmlSeeAlso({ObjectFactory.class})
public interface Ec {

    @WebMethod(action = "http://www.example.org/Ec/callService")
    @RequestWrapper(localName = "callService", targetNamespace = "http://www.example.org/Ec/", className = "com.puer.wsclient.ykd.api.CallService")
    @ResponseWrapper(localName = "callServiceResponse", targetNamespace = "http://www.example.org/Ec/", className = "com.puer.wsclient.ykd.api.CallServiceResponse")
    @WebResult(name = "response", targetNamespace = "")
    public java.lang.String callService(
        @WebParam(name = "paramsJson", targetNamespace = "")
        java.lang.String paramsJson,
        @WebParam(name = "appToken", targetNamespace = "")
        java.lang.String appToken,
        @WebParam(name = "appKey", targetNamespace = "")
        java.lang.String appKey,
        @WebParam(name = "service", targetNamespace = "")
        java.lang.String service
    );
}
