package com.puer.wsclient.ykd.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-22T09:51:49.959+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "Ec", 
                  wsdlLocation = "http://202.104.134.94:7181/default/svc/wsdl",
                  targetNamespace = "http://www.example.org/Ec/") 
public class Ec_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/Ec/", "Ec");
    public final static QName EcSOAP = new QName("http://www.example.org/Ec/", "EcSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://202.104.134.94:7181/default/svc/wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Ec_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://202.104.134.94:7181/default/svc/wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Ec_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Ec_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ec_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Ec_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Ec_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Ec_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Ec
     */
    @WebEndpoint(name = "EcSOAP")
    public Ec getEcSOAP() {
        return super.getPort(EcSOAP, Ec.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ec
     */
    @WebEndpoint(name = "EcSOAP")
    public Ec getEcSOAP(WebServiceFeature... features) {
        return super.getPort(EcSOAP, Ec.class, features);
    }

}
